@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix sh:    <http://www.w3.org/ns/shacl#> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix ex:    <http://www.example.org/#> .
@prefix owl:   <http://www.w3.org/2002/07/owl#> .
@prefix pmd:   <https://w3id.org/pmd/co/> .
@prefix obo: <http://purl.obolibrary.org/obo/> .
@prefix obi: <http://purl.obolibrary.org/obo/obi.owl#>
@prefix iao: <http://purl.obolibrary.org/obo/iao.owl#> .
@prefix isk: <https://tib.eu/ontologies/isk/> .
@prefix dro: <https://www.tib.eu/digitrubber#> .


##########################################################################
#Individuals
##########################################################################

###  <http://purl.obolibrary.org/obo/obi.owl#scalar_value_specification_StearicAcid_ActualMass_EPDM>
<http://purl.obolibrary.org/obo/obi.owl#scalar_value_specification_StearicAcid_ActualMass_EPDM> rdf:type owl:NamedIndividual ,
<http://purl.obolibrary.org/obo/OBI_0001931> ;
#add properties 
#specifies value of
<http://purl.obolibrary.org/obo/OBI_0001927> <http://purl.obolibrary.org/obo/PATO_0000125> ;
#has specified numeric value
<http://purl.obolibrary.org/obo/OBI_0001937> 12.0^^xsd:float ;
<http://purl.obolibrary.org/obo/IAO_0000039> dro:DIGITRUBBER_000335 .
